---
# handlers file for etcd
- name: restart {{ service_name }}
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted

- name: stop {{ service_name }}
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: stopped

- name: reload {{ service_name }}
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: reloaded

- name: systemctl daemon-reload
  systemd:
    daemon_reload: true